# -*- coding: utf-8 -*-
"""PySpark_persist.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VL1YEdxIh5BspmVepd-AxSRtBwngSsVh
"""

pip install pyspark

"""from pyspark.sql import SparkSession

"""

from pyspark.sql import SparkSession

spark = SparkSession.builder.master("local[4]")\
        .appName('MITU_Skillologies')\
        .getOrCreate()

# spark context object
sc = spark.sparkContext

df1 = spark.read.option('header', True).csv('student.csv')

df_cache = df1.cache()

df_cache.show()

import pyspark

df_persist = df1.persist(pyspark.StorageLevel.DISK_ONLY) # storage location is DISK_ONLY

df_persist.show()

"""Unpersist

"""

df_persist.unpersist()

df_persist.show()

df_cache.unpersist()

